"""new col in files

Revision ID: ed8a48cf775d
Revises: cac2e533b7f1
Create Date: 2026-05-25 13:24:06.310349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed8a48cf775d'
down_revision: Union[str, Sequence[str], None] = 'cac2e533b7f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('total_files_test', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'total_files_test')
    # ### end Alembic commands ###
