"""test_str added

Revision ID: f578605e782e
Revises: ed8a48cf775d
Create Date: 2026-05-25 13:31:31.820121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f578605e782e'
down_revision: Union[str, Sequence[str], None] = 'ed8a48cf775d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('test_str', sa.String(), nullable=False, server_default='hello'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'test_str')
    # ### end Alembic commands ###
